# Exported from:        http://release-staging.devops.dev.digitalai.cloud/
# Release version:      24.1.0-beta.5
# Date created:         Fri Feb 16 11:36:31 GMT 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Connections.yaml
  - Notifications.yaml
  - Workflow_Delete Application in ArgoCD.yaml
  - Workflow_Install Argo Rollouts.yaml
  - Workflow_Install ArgoCD.yaml
  - Workflow_Setup ArgoCD application with initial deployment.yaml
