# Exported from:        http://localhost:5516/
# Release version:      24.1.0-301.113
# Date created:         Fri Mar 01 10:25:42 GMT 2024

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_Parent template.yaml
