# Exported from:        http://release:5516/
# Release version:      24.3.0
# Date created:         Fri Feb 07 08:36:24 GMT 2025

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Template_Test Runner for Templates.yaml
