# Exported from:        http://host.docker.internal:5516/
# Release version:      23.3.0
# Date created:         Fri Nov 24 10:20:55 UTC 2023

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Workflow_Hello world.yaml
