# Exported from:        http://localhost:5516/
# Release version:      23.3.0-711.113
# Date created:         Tue Jul 11 14:55:12 UTC 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: workflows
spec:
- directory: Digital.ai Deploy
