# Exported from:        http://host.docker.internal:5516/
# Release version:      23.3.0-beta.5
# Date created:         Fri Aug 18 18:25:52 UTC 2023

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Workflow_Create new repo.yaml
