# Exported from:        http://host.docker.internal:5516/
# Release version:      23.3.0-beta.5
# Date created:         Fri Aug 18 18:25:52 UTC 2023

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Team Workflows
spec:
- template: Create new repo
  phases:
  - phase: Steps
    tasks:
    - name: Project properties
      type: xlrelease.UserInputTask
      description: Enter the properties of the new project
      variables:
      - product
      - module
      - type
      - language
      - team
    - name: Create repo from template
      type: githubhes.CreateRepoFromTemplate
      description: |-
        Go to the [python-template](https://github.com/Hes-Siemelink/python-template) template repository  on GitHub and select **New repo from template**

        Use the naming convention: `${product}-${module}-${type}`
      variableMapping:
        repository: "${repo}"
      capabilities:
      - remote
      repoName: "${product}-${module}-${type}"
      template: Hes-Siemelink/python-template
      token: !value "githubhes_CreateRepoFromTemplate_Create_repo_from_template_token"
    - name: Customize project
      type: githubhes.ModifyFile
      description: "In the Readme of [repository ${repo}](https://github.com/${repo}),\
        \ replace `PROJECT_NAME` and `TEAM_NAME` with the actual values."
      capabilities:
      - remote
      repoName: "${repo}"
      token: !value "githubhes_ModifyFile_Customize_project_token"
      branch: main
      path: README.md
      content: |-
        # ${product}  ${module} (${type})

        Maintained by team ${team}


        ## Install

        Click the [Use this template](https://github.com/Justintime50/python-template/generate) button at the top of this project's GitHub page to get started.

        ## Usage

        ### Easy text replacements

        1. Replace all instances of `project_name` with the name of your project
            * These are the Python snake_case references (eg: `project_name`)
        1. Replace all instances of `PROJECT_NAME_URL` with the name of your project
            * These are the references to your project that will appear in URLs and are typically hyphenated (eg: `project-name`)
        1. Replace all instances of `USERNAME` with the name of the author or owner of the project
            * These are references typically found in the URL of your project as it appears on GitHub

        ### File configuration

        1. Configure the `setup.py` file
        1. Configure the `Makefile` targets
        1. Update the name in the `LICENSE` or swap it out entirely
        1. Configure the `.github/workflows/build.yml` file
        1. Update the `CHANGELOG.md` with your own info
        1. Rename other files/folders as needed and configure their content
        1. Delete this `README` and rename `README_project.md` to `README.md`
      message: Updated README with project info
    - name: Closing message
      type: xlrelease.Task
      description: |-
        The new repository **[${repo}](https://github.com/${repo})** has been created.

        Check it out!
    color: '#3d6c9e'
  kind: WORKFLOW
  categories:
  - Application Life Cycle Management
  variables:
  - type: xlrelease.StringVariable
    key: module
    requiresValue: false
    showOnReleaseStart: false
    label: Module
    description: New module that is created
  - type: xlrelease.StringVariable
    key: product
    showOnReleaseStart: false
    label: Product
    description: Main product this repo is for.
  - type: xlrelease.StringVariable
    key: language
    showOnReleaseStart: false
    label: Language
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - Python
      - JavaScript
      - Go
      - Java
    value: Python
  - type: xlrelease.StringVariable
    key: type
    showOnReleaseStart: false
    label: Project type
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - frontend
      - backend
      - integration-tests
      - demo-material
    value: backend
  - type: xlrelease.StringVariable
    key: team
    showOnReleaseStart: false
    label: Team name
    description: The team responsible for the project
  - type: xlrelease.StringVariable
    key: repo
    requiresValue: false
    showOnReleaseStart: false
